CREATE DATABASE IF NOT EXISTS TREADMAPS;
USE DATABASE TREADMAPS;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;
USE SCHEMA ANALYTICS;

CREATE TABLE IF NOT EXISTS ROUTE_EVENTS (
    event_id VARCHAR(36) DEFAULT UUID_STRING(),
    timestamp TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    route_mode VARCHAR(20),
    score FLOAT,
    temperature FLOAT,
    precipitation FLOAT,
    user_fatigue FLOAT
);

CREATE TABLE IF NOT EXISTS ENVIRONMENTAL_RISK (
    event_id VARCHAR(36) DEFAULT UUID_STRING(),
    timestamp TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    temperature FLOAT,
    wind_speed FLOAT,
    precipitation FLOAT,
    risk_score FLOAT
);